slam_config_path: "/home/mvonarnim/colcon_ws/src/SaDVIO/ros/config"
gnss_topic: "fix" #"/ublox_driver/receiver_lla"

thresh_cov: 60
window_size: 200
remove_z_estimate: True
T_a_f: [1., 0., 0., -0.1,
  0., 1., 0., 0.,
  0., 0., 1., 0.1,
  0., 0., 0., 1.]